
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `KPIResult` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model KPIResult
 * 
 */
export type KPIResultModel = runtime.Types.Result.DefaultSelection<Prisma.$KPIResultPayload>

export type AggregateKPIResult = {
  _count: KPIResultCountAggregateOutputType | null
  _min: KPIResultMinAggregateOutputType | null
  _max: KPIResultMaxAggregateOutputType | null
}

export type KPIResultMinAggregateOutputType = {
  id: string | null
  submissionId: string | null
  name: string | null
  target: string | null
  achieved: string | null
  status: string | null
}

export type KPIResultMaxAggregateOutputType = {
  id: string | null
  submissionId: string | null
  name: string | null
  target: string | null
  achieved: string | null
  status: string | null
}

export type KPIResultCountAggregateOutputType = {
  id: number
  submissionId: number
  name: number
  target: number
  achieved: number
  status: number
  _all: number
}


export type KPIResultMinAggregateInputType = {
  id?: true
  submissionId?: true
  name?: true
  target?: true
  achieved?: true
  status?: true
}

export type KPIResultMaxAggregateInputType = {
  id?: true
  submissionId?: true
  name?: true
  target?: true
  achieved?: true
  status?: true
}

export type KPIResultCountAggregateInputType = {
  id?: true
  submissionId?: true
  name?: true
  target?: true
  achieved?: true
  status?: true
  _all?: true
}

export type KPIResultAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KPIResult to aggregate.
   */
  where?: Prisma.KPIResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KPIResults to fetch.
   */
  orderBy?: Prisma.KPIResultOrderByWithRelationInput | Prisma.KPIResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KPIResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KPIResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KPIResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned KPIResults
  **/
  _count?: true | KPIResultCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KPIResultMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KPIResultMaxAggregateInputType
}

export type GetKPIResultAggregateType<T extends KPIResultAggregateArgs> = {
      [P in keyof T & keyof AggregateKPIResult]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKPIResult[P]>
    : Prisma.GetScalarType<T[P], AggregateKPIResult[P]>
}




export type KPIResultGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KPIResultWhereInput
  orderBy?: Prisma.KPIResultOrderByWithAggregationInput | Prisma.KPIResultOrderByWithAggregationInput[]
  by: Prisma.KPIResultScalarFieldEnum[] | Prisma.KPIResultScalarFieldEnum
  having?: Prisma.KPIResultScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KPIResultCountAggregateInputType | true
  _min?: KPIResultMinAggregateInputType
  _max?: KPIResultMaxAggregateInputType
}

export type KPIResultGroupByOutputType = {
  id: string
  submissionId: string
  name: string
  target: string
  achieved: string
  status: string
  _count: KPIResultCountAggregateOutputType | null
  _min: KPIResultMinAggregateOutputType | null
  _max: KPIResultMaxAggregateOutputType | null
}

type GetKPIResultGroupByPayload<T extends KPIResultGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KPIResultGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KPIResultGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KPIResultGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KPIResultGroupByOutputType[P]>
      }
    >
  >



export type KPIResultWhereInput = {
  AND?: Prisma.KPIResultWhereInput | Prisma.KPIResultWhereInput[]
  OR?: Prisma.KPIResultWhereInput[]
  NOT?: Prisma.KPIResultWhereInput | Prisma.KPIResultWhereInput[]
  id?: Prisma.StringFilter<"KPIResult"> | string
  submissionId?: Prisma.StringFilter<"KPIResult"> | string
  name?: Prisma.StringFilter<"KPIResult"> | string
  target?: Prisma.StringFilter<"KPIResult"> | string
  achieved?: Prisma.StringFilter<"KPIResult"> | string
  status?: Prisma.StringFilter<"KPIResult"> | string
  submission?: Prisma.XOR<Prisma.SubmissionScalarRelationFilter, Prisma.SubmissionWhereInput>
}

export type KPIResultOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  submissionId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  target?: Prisma.SortOrder
  achieved?: Prisma.SortOrder
  status?: Prisma.SortOrder
  submission?: Prisma.SubmissionOrderByWithRelationInput
}

export type KPIResultWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.KPIResultWhereInput | Prisma.KPIResultWhereInput[]
  OR?: Prisma.KPIResultWhereInput[]
  NOT?: Prisma.KPIResultWhereInput | Prisma.KPIResultWhereInput[]
  submissionId?: Prisma.StringFilter<"KPIResult"> | string
  name?: Prisma.StringFilter<"KPIResult"> | string
  target?: Prisma.StringFilter<"KPIResult"> | string
  achieved?: Prisma.StringFilter<"KPIResult"> | string
  status?: Prisma.StringFilter<"KPIResult"> | string
  submission?: Prisma.XOR<Prisma.SubmissionScalarRelationFilter, Prisma.SubmissionWhereInput>
}, "id">

export type KPIResultOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  submissionId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  target?: Prisma.SortOrder
  achieved?: Prisma.SortOrder
  status?: Prisma.SortOrder
  _count?: Prisma.KPIResultCountOrderByAggregateInput
  _max?: Prisma.KPIResultMaxOrderByAggregateInput
  _min?: Prisma.KPIResultMinOrderByAggregateInput
}

export type KPIResultScalarWhereWithAggregatesInput = {
  AND?: Prisma.KPIResultScalarWhereWithAggregatesInput | Prisma.KPIResultScalarWhereWithAggregatesInput[]
  OR?: Prisma.KPIResultScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KPIResultScalarWhereWithAggregatesInput | Prisma.KPIResultScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"KPIResult"> | string
  submissionId?: Prisma.StringWithAggregatesFilter<"KPIResult"> | string
  name?: Prisma.StringWithAggregatesFilter<"KPIResult"> | string
  target?: Prisma.StringWithAggregatesFilter<"KPIResult"> | string
  achieved?: Prisma.StringWithAggregatesFilter<"KPIResult"> | string
  status?: Prisma.StringWithAggregatesFilter<"KPIResult"> | string
}

export type KPIResultCreateInput = {
  id?: string
  name: string
  target: string
  achieved: string
  status: string
  submission: Prisma.SubmissionCreateNestedOneWithoutKpiResultsInput
}

export type KPIResultUncheckedCreateInput = {
  id?: string
  submissionId: string
  name: string
  target: string
  achieved: string
  status: string
}

export type KPIResultUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.StringFieldUpdateOperationsInput | string
  achieved?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  submission?: Prisma.SubmissionUpdateOneRequiredWithoutKpiResultsNestedInput
}

export type KPIResultUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  submissionId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.StringFieldUpdateOperationsInput | string
  achieved?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type KPIResultCreateManyInput = {
  id?: string
  submissionId: string
  name: string
  target: string
  achieved: string
  status: string
}

export type KPIResultUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.StringFieldUpdateOperationsInput | string
  achieved?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type KPIResultUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  submissionId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.StringFieldUpdateOperationsInput | string
  achieved?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type KPIResultListRelationFilter = {
  every?: Prisma.KPIResultWhereInput
  some?: Prisma.KPIResultWhereInput
  none?: Prisma.KPIResultWhereInput
}

export type KPIResultOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type KPIResultCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  submissionId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  target?: Prisma.SortOrder
  achieved?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type KPIResultMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  submissionId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  target?: Prisma.SortOrder
  achieved?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type KPIResultMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  submissionId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  target?: Prisma.SortOrder
  achieved?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type KPIResultCreateNestedManyWithoutSubmissionInput = {
  create?: Prisma.XOR<Prisma.KPIResultCreateWithoutSubmissionInput, Prisma.KPIResultUncheckedCreateWithoutSubmissionInput> | Prisma.KPIResultCreateWithoutSubmissionInput[] | Prisma.KPIResultUncheckedCreateWithoutSubmissionInput[]
  connectOrCreate?: Prisma.KPIResultCreateOrConnectWithoutSubmissionInput | Prisma.KPIResultCreateOrConnectWithoutSubmissionInput[]
  createMany?: Prisma.KPIResultCreateManySubmissionInputEnvelope
  connect?: Prisma.KPIResultWhereUniqueInput | Prisma.KPIResultWhereUniqueInput[]
}

export type KPIResultUncheckedCreateNestedManyWithoutSubmissionInput = {
  create?: Prisma.XOR<Prisma.KPIResultCreateWithoutSubmissionInput, Prisma.KPIResultUncheckedCreateWithoutSubmissionInput> | Prisma.KPIResultCreateWithoutSubmissionInput[] | Prisma.KPIResultUncheckedCreateWithoutSubmissionInput[]
  connectOrCreate?: Prisma.KPIResultCreateOrConnectWithoutSubmissionInput | Prisma.KPIResultCreateOrConnectWithoutSubmissionInput[]
  createMany?: Prisma.KPIResultCreateManySubmissionInputEnvelope
  connect?: Prisma.KPIResultWhereUniqueInput | Prisma.KPIResultWhereUniqueInput[]
}

export type KPIResultUpdateManyWithoutSubmissionNestedInput = {
  create?: Prisma.XOR<Prisma.KPIResultCreateWithoutSubmissionInput, Prisma.KPIResultUncheckedCreateWithoutSubmissionInput> | Prisma.KPIResultCreateWithoutSubmissionInput[] | Prisma.KPIResultUncheckedCreateWithoutSubmissionInput[]
  connectOrCreate?: Prisma.KPIResultCreateOrConnectWithoutSubmissionInput | Prisma.KPIResultCreateOrConnectWithoutSubmissionInput[]
  upsert?: Prisma.KPIResultUpsertWithWhereUniqueWithoutSubmissionInput | Prisma.KPIResultUpsertWithWhereUniqueWithoutSubmissionInput[]
  createMany?: Prisma.KPIResultCreateManySubmissionInputEnvelope
  set?: Prisma.KPIResultWhereUniqueInput | Prisma.KPIResultWhereUniqueInput[]
  disconnect?: Prisma.KPIResultWhereUniqueInput | Prisma.KPIResultWhereUniqueInput[]
  delete?: Prisma.KPIResultWhereUniqueInput | Prisma.KPIResultWhereUniqueInput[]
  connect?: Prisma.KPIResultWhereUniqueInput | Prisma.KPIResultWhereUniqueInput[]
  update?: Prisma.KPIResultUpdateWithWhereUniqueWithoutSubmissionInput | Prisma.KPIResultUpdateWithWhereUniqueWithoutSubmissionInput[]
  updateMany?: Prisma.KPIResultUpdateManyWithWhereWithoutSubmissionInput | Prisma.KPIResultUpdateManyWithWhereWithoutSubmissionInput[]
  deleteMany?: Prisma.KPIResultScalarWhereInput | Prisma.KPIResultScalarWhereInput[]
}

export type KPIResultUncheckedUpdateManyWithoutSubmissionNestedInput = {
  create?: Prisma.XOR<Prisma.KPIResultCreateWithoutSubmissionInput, Prisma.KPIResultUncheckedCreateWithoutSubmissionInput> | Prisma.KPIResultCreateWithoutSubmissionInput[] | Prisma.KPIResultUncheckedCreateWithoutSubmissionInput[]
  connectOrCreate?: Prisma.KPIResultCreateOrConnectWithoutSubmissionInput | Prisma.KPIResultCreateOrConnectWithoutSubmissionInput[]
  upsert?: Prisma.KPIResultUpsertWithWhereUniqueWithoutSubmissionInput | Prisma.KPIResultUpsertWithWhereUniqueWithoutSubmissionInput[]
  createMany?: Prisma.KPIResultCreateManySubmissionInputEnvelope
  set?: Prisma.KPIResultWhereUniqueInput | Prisma.KPIResultWhereUniqueInput[]
  disconnect?: Prisma.KPIResultWhereUniqueInput | Prisma.KPIResultWhereUniqueInput[]
  delete?: Prisma.KPIResultWhereUniqueInput | Prisma.KPIResultWhereUniqueInput[]
  connect?: Prisma.KPIResultWhereUniqueInput | Prisma.KPIResultWhereUniqueInput[]
  update?: Prisma.KPIResultUpdateWithWhereUniqueWithoutSubmissionInput | Prisma.KPIResultUpdateWithWhereUniqueWithoutSubmissionInput[]
  updateMany?: Prisma.KPIResultUpdateManyWithWhereWithoutSubmissionInput | Prisma.KPIResultUpdateManyWithWhereWithoutSubmissionInput[]
  deleteMany?: Prisma.KPIResultScalarWhereInput | Prisma.KPIResultScalarWhereInput[]
}

export type KPIResultCreateWithoutSubmissionInput = {
  id?: string
  name: string
  target: string
  achieved: string
  status: string
}

export type KPIResultUncheckedCreateWithoutSubmissionInput = {
  id?: string
  name: string
  target: string
  achieved: string
  status: string
}

export type KPIResultCreateOrConnectWithoutSubmissionInput = {
  where: Prisma.KPIResultWhereUniqueInput
  create: Prisma.XOR<Prisma.KPIResultCreateWithoutSubmissionInput, Prisma.KPIResultUncheckedCreateWithoutSubmissionInput>
}

export type KPIResultCreateManySubmissionInputEnvelope = {
  data: Prisma.KPIResultCreateManySubmissionInput | Prisma.KPIResultCreateManySubmissionInput[]
  skipDuplicates?: boolean
}

export type KPIResultUpsertWithWhereUniqueWithoutSubmissionInput = {
  where: Prisma.KPIResultWhereUniqueInput
  update: Prisma.XOR<Prisma.KPIResultUpdateWithoutSubmissionInput, Prisma.KPIResultUncheckedUpdateWithoutSubmissionInput>
  create: Prisma.XOR<Prisma.KPIResultCreateWithoutSubmissionInput, Prisma.KPIResultUncheckedCreateWithoutSubmissionInput>
}

export type KPIResultUpdateWithWhereUniqueWithoutSubmissionInput = {
  where: Prisma.KPIResultWhereUniqueInput
  data: Prisma.XOR<Prisma.KPIResultUpdateWithoutSubmissionInput, Prisma.KPIResultUncheckedUpdateWithoutSubmissionInput>
}

export type KPIResultUpdateManyWithWhereWithoutSubmissionInput = {
  where: Prisma.KPIResultScalarWhereInput
  data: Prisma.XOR<Prisma.KPIResultUpdateManyMutationInput, Prisma.KPIResultUncheckedUpdateManyWithoutSubmissionInput>
}

export type KPIResultScalarWhereInput = {
  AND?: Prisma.KPIResultScalarWhereInput | Prisma.KPIResultScalarWhereInput[]
  OR?: Prisma.KPIResultScalarWhereInput[]
  NOT?: Prisma.KPIResultScalarWhereInput | Prisma.KPIResultScalarWhereInput[]
  id?: Prisma.StringFilter<"KPIResult"> | string
  submissionId?: Prisma.StringFilter<"KPIResult"> | string
  name?: Prisma.StringFilter<"KPIResult"> | string
  target?: Prisma.StringFilter<"KPIResult"> | string
  achieved?: Prisma.StringFilter<"KPIResult"> | string
  status?: Prisma.StringFilter<"KPIResult"> | string
}

export type KPIResultCreateManySubmissionInput = {
  id?: string
  name: string
  target: string
  achieved: string
  status: string
}

export type KPIResultUpdateWithoutSubmissionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.StringFieldUpdateOperationsInput | string
  achieved?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type KPIResultUncheckedUpdateWithoutSubmissionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.StringFieldUpdateOperationsInput | string
  achieved?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}

export type KPIResultUncheckedUpdateManyWithoutSubmissionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.StringFieldUpdateOperationsInput | string
  achieved?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
}



export type KPIResultSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  submissionId?: boolean
  name?: boolean
  target?: boolean
  achieved?: boolean
  status?: boolean
  submission?: boolean | Prisma.SubmissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kPIResult"]>

export type KPIResultSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  submissionId?: boolean
  name?: boolean
  target?: boolean
  achieved?: boolean
  status?: boolean
  submission?: boolean | Prisma.SubmissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kPIResult"]>

export type KPIResultSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  submissionId?: boolean
  name?: boolean
  target?: boolean
  achieved?: boolean
  status?: boolean
  submission?: boolean | Prisma.SubmissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kPIResult"]>

export type KPIResultSelectScalar = {
  id?: boolean
  submissionId?: boolean
  name?: boolean
  target?: boolean
  achieved?: boolean
  status?: boolean
}

export type KPIResultOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "submissionId" | "name" | "target" | "achieved" | "status", ExtArgs["result"]["kPIResult"]>
export type KPIResultInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  submission?: boolean | Prisma.SubmissionDefaultArgs<ExtArgs>
}
export type KPIResultIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  submission?: boolean | Prisma.SubmissionDefaultArgs<ExtArgs>
}
export type KPIResultIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  submission?: boolean | Prisma.SubmissionDefaultArgs<ExtArgs>
}

export type $KPIResultPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "KPIResult"
  objects: {
    submission: Prisma.$SubmissionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    submissionId: string
    name: string
    target: string
    achieved: string
    status: string
  }, ExtArgs["result"]["kPIResult"]>
  composites: {}
}

export type KPIResultGetPayload<S extends boolean | null | undefined | KPIResultDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KPIResultPayload, S>

export type KPIResultCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KPIResultFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KPIResultCountAggregateInputType | true
  }

export interface KPIResultDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['KPIResult'], meta: { name: 'KPIResult' } }
  /**
   * Find zero or one KPIResult that matches the filter.
   * @param {KPIResultFindUniqueArgs} args - Arguments to find a KPIResult
   * @example
   * // Get one KPIResult
   * const kPIResult = await prisma.kPIResult.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KPIResultFindUniqueArgs>(args: Prisma.SelectSubset<T, KPIResultFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KPIResultClient<runtime.Types.Result.GetResult<Prisma.$KPIResultPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one KPIResult that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KPIResultFindUniqueOrThrowArgs} args - Arguments to find a KPIResult
   * @example
   * // Get one KPIResult
   * const kPIResult = await prisma.kPIResult.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KPIResultFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KPIResultFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KPIResultClient<runtime.Types.Result.GetResult<Prisma.$KPIResultPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KPIResult that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KPIResultFindFirstArgs} args - Arguments to find a KPIResult
   * @example
   * // Get one KPIResult
   * const kPIResult = await prisma.kPIResult.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KPIResultFindFirstArgs>(args?: Prisma.SelectSubset<T, KPIResultFindFirstArgs<ExtArgs>>): Prisma.Prisma__KPIResultClient<runtime.Types.Result.GetResult<Prisma.$KPIResultPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KPIResult that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KPIResultFindFirstOrThrowArgs} args - Arguments to find a KPIResult
   * @example
   * // Get one KPIResult
   * const kPIResult = await prisma.kPIResult.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KPIResultFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KPIResultFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KPIResultClient<runtime.Types.Result.GetResult<Prisma.$KPIResultPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more KPIResults that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KPIResultFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all KPIResults
   * const kPIResults = await prisma.kPIResult.findMany()
   * 
   * // Get first 10 KPIResults
   * const kPIResults = await prisma.kPIResult.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const kPIResultWithIdOnly = await prisma.kPIResult.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends KPIResultFindManyArgs>(args?: Prisma.SelectSubset<T, KPIResultFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KPIResultPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a KPIResult.
   * @param {KPIResultCreateArgs} args - Arguments to create a KPIResult.
   * @example
   * // Create one KPIResult
   * const KPIResult = await prisma.kPIResult.create({
   *   data: {
   *     // ... data to create a KPIResult
   *   }
   * })
   * 
   */
  create<T extends KPIResultCreateArgs>(args: Prisma.SelectSubset<T, KPIResultCreateArgs<ExtArgs>>): Prisma.Prisma__KPIResultClient<runtime.Types.Result.GetResult<Prisma.$KPIResultPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many KPIResults.
   * @param {KPIResultCreateManyArgs} args - Arguments to create many KPIResults.
   * @example
   * // Create many KPIResults
   * const kPIResult = await prisma.kPIResult.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends KPIResultCreateManyArgs>(args?: Prisma.SelectSubset<T, KPIResultCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many KPIResults and returns the data saved in the database.
   * @param {KPIResultCreateManyAndReturnArgs} args - Arguments to create many KPIResults.
   * @example
   * // Create many KPIResults
   * const kPIResult = await prisma.kPIResult.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many KPIResults and only return the `id`
   * const kPIResultWithIdOnly = await prisma.kPIResult.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends KPIResultCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, KPIResultCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KPIResultPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a KPIResult.
   * @param {KPIResultDeleteArgs} args - Arguments to delete one KPIResult.
   * @example
   * // Delete one KPIResult
   * const KPIResult = await prisma.kPIResult.delete({
   *   where: {
   *     // ... filter to delete one KPIResult
   *   }
   * })
   * 
   */
  delete<T extends KPIResultDeleteArgs>(args: Prisma.SelectSubset<T, KPIResultDeleteArgs<ExtArgs>>): Prisma.Prisma__KPIResultClient<runtime.Types.Result.GetResult<Prisma.$KPIResultPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one KPIResult.
   * @param {KPIResultUpdateArgs} args - Arguments to update one KPIResult.
   * @example
   * // Update one KPIResult
   * const kPIResult = await prisma.kPIResult.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KPIResultUpdateArgs>(args: Prisma.SelectSubset<T, KPIResultUpdateArgs<ExtArgs>>): Prisma.Prisma__KPIResultClient<runtime.Types.Result.GetResult<Prisma.$KPIResultPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more KPIResults.
   * @param {KPIResultDeleteManyArgs} args - Arguments to filter KPIResults to delete.
   * @example
   * // Delete a few KPIResults
   * const { count } = await prisma.kPIResult.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KPIResultDeleteManyArgs>(args?: Prisma.SelectSubset<T, KPIResultDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KPIResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KPIResultUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many KPIResults
   * const kPIResult = await prisma.kPIResult.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KPIResultUpdateManyArgs>(args: Prisma.SelectSubset<T, KPIResultUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KPIResults and returns the data updated in the database.
   * @param {KPIResultUpdateManyAndReturnArgs} args - Arguments to update many KPIResults.
   * @example
   * // Update many KPIResults
   * const kPIResult = await prisma.kPIResult.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more KPIResults and only return the `id`
   * const kPIResultWithIdOnly = await prisma.kPIResult.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends KPIResultUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, KPIResultUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KPIResultPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one KPIResult.
   * @param {KPIResultUpsertArgs} args - Arguments to update or create a KPIResult.
   * @example
   * // Update or create a KPIResult
   * const kPIResult = await prisma.kPIResult.upsert({
   *   create: {
   *     // ... data to create a KPIResult
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the KPIResult we want to update
   *   }
   * })
   */
  upsert<T extends KPIResultUpsertArgs>(args: Prisma.SelectSubset<T, KPIResultUpsertArgs<ExtArgs>>): Prisma.Prisma__KPIResultClient<runtime.Types.Result.GetResult<Prisma.$KPIResultPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of KPIResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KPIResultCountArgs} args - Arguments to filter KPIResults to count.
   * @example
   * // Count the number of KPIResults
   * const count = await prisma.kPIResult.count({
   *   where: {
   *     // ... the filter for the KPIResults we want to count
   *   }
   * })
  **/
  count<T extends KPIResultCountArgs>(
    args?: Prisma.Subset<T, KPIResultCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KPIResultCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a KPIResult.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KPIResultAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KPIResultAggregateArgs>(args: Prisma.Subset<T, KPIResultAggregateArgs>): Prisma.PrismaPromise<GetKPIResultAggregateType<T>>

  /**
   * Group by KPIResult.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KPIResultGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KPIResultGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KPIResultGroupByArgs['orderBy'] }
      : { orderBy?: KPIResultGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KPIResultGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKPIResultGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the KPIResult model
 */
readonly fields: KPIResultFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for KPIResult.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KPIResultClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  submission<T extends Prisma.SubmissionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubmissionDefaultArgs<ExtArgs>>): Prisma.Prisma__SubmissionClient<runtime.Types.Result.GetResult<Prisma.$SubmissionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the KPIResult model
 */
export interface KPIResultFieldRefs {
  readonly id: Prisma.FieldRef<"KPIResult", 'String'>
  readonly submissionId: Prisma.FieldRef<"KPIResult", 'String'>
  readonly name: Prisma.FieldRef<"KPIResult", 'String'>
  readonly target: Prisma.FieldRef<"KPIResult", 'String'>
  readonly achieved: Prisma.FieldRef<"KPIResult", 'String'>
  readonly status: Prisma.FieldRef<"KPIResult", 'String'>
}
    

// Custom InputTypes
/**
 * KPIResult findUnique
 */
export type KPIResultFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KPIResult
   */
  select?: Prisma.KPIResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KPIResult
   */
  omit?: Prisma.KPIResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KPIResultInclude<ExtArgs> | null
  /**
   * Filter, which KPIResult to fetch.
   */
  where: Prisma.KPIResultWhereUniqueInput
}

/**
 * KPIResult findUniqueOrThrow
 */
export type KPIResultFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KPIResult
   */
  select?: Prisma.KPIResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KPIResult
   */
  omit?: Prisma.KPIResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KPIResultInclude<ExtArgs> | null
  /**
   * Filter, which KPIResult to fetch.
   */
  where: Prisma.KPIResultWhereUniqueInput
}

/**
 * KPIResult findFirst
 */
export type KPIResultFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KPIResult
   */
  select?: Prisma.KPIResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KPIResult
   */
  omit?: Prisma.KPIResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KPIResultInclude<ExtArgs> | null
  /**
   * Filter, which KPIResult to fetch.
   */
  where?: Prisma.KPIResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KPIResults to fetch.
   */
  orderBy?: Prisma.KPIResultOrderByWithRelationInput | Prisma.KPIResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KPIResults.
   */
  cursor?: Prisma.KPIResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KPIResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KPIResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KPIResults.
   */
  distinct?: Prisma.KPIResultScalarFieldEnum | Prisma.KPIResultScalarFieldEnum[]
}

/**
 * KPIResult findFirstOrThrow
 */
export type KPIResultFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KPIResult
   */
  select?: Prisma.KPIResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KPIResult
   */
  omit?: Prisma.KPIResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KPIResultInclude<ExtArgs> | null
  /**
   * Filter, which KPIResult to fetch.
   */
  where?: Prisma.KPIResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KPIResults to fetch.
   */
  orderBy?: Prisma.KPIResultOrderByWithRelationInput | Prisma.KPIResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KPIResults.
   */
  cursor?: Prisma.KPIResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KPIResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KPIResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KPIResults.
   */
  distinct?: Prisma.KPIResultScalarFieldEnum | Prisma.KPIResultScalarFieldEnum[]
}

/**
 * KPIResult findMany
 */
export type KPIResultFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KPIResult
   */
  select?: Prisma.KPIResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KPIResult
   */
  omit?: Prisma.KPIResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KPIResultInclude<ExtArgs> | null
  /**
   * Filter, which KPIResults to fetch.
   */
  where?: Prisma.KPIResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KPIResults to fetch.
   */
  orderBy?: Prisma.KPIResultOrderByWithRelationInput | Prisma.KPIResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing KPIResults.
   */
  cursor?: Prisma.KPIResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KPIResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KPIResults.
   */
  skip?: number
  distinct?: Prisma.KPIResultScalarFieldEnum | Prisma.KPIResultScalarFieldEnum[]
}

/**
 * KPIResult create
 */
export type KPIResultCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KPIResult
   */
  select?: Prisma.KPIResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KPIResult
   */
  omit?: Prisma.KPIResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KPIResultInclude<ExtArgs> | null
  /**
   * The data needed to create a KPIResult.
   */
  data: Prisma.XOR<Prisma.KPIResultCreateInput, Prisma.KPIResultUncheckedCreateInput>
}

/**
 * KPIResult createMany
 */
export type KPIResultCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many KPIResults.
   */
  data: Prisma.KPIResultCreateManyInput | Prisma.KPIResultCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * KPIResult createManyAndReturn
 */
export type KPIResultCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KPIResult
   */
  select?: Prisma.KPIResultSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KPIResult
   */
  omit?: Prisma.KPIResultOmit<ExtArgs> | null
  /**
   * The data used to create many KPIResults.
   */
  data: Prisma.KPIResultCreateManyInput | Prisma.KPIResultCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KPIResultIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * KPIResult update
 */
export type KPIResultUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KPIResult
   */
  select?: Prisma.KPIResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KPIResult
   */
  omit?: Prisma.KPIResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KPIResultInclude<ExtArgs> | null
  /**
   * The data needed to update a KPIResult.
   */
  data: Prisma.XOR<Prisma.KPIResultUpdateInput, Prisma.KPIResultUncheckedUpdateInput>
  /**
   * Choose, which KPIResult to update.
   */
  where: Prisma.KPIResultWhereUniqueInput
}

/**
 * KPIResult updateMany
 */
export type KPIResultUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update KPIResults.
   */
  data: Prisma.XOR<Prisma.KPIResultUpdateManyMutationInput, Prisma.KPIResultUncheckedUpdateManyInput>
  /**
   * Filter which KPIResults to update
   */
  where?: Prisma.KPIResultWhereInput
  /**
   * Limit how many KPIResults to update.
   */
  limit?: number
}

/**
 * KPIResult updateManyAndReturn
 */
export type KPIResultUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KPIResult
   */
  select?: Prisma.KPIResultSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KPIResult
   */
  omit?: Prisma.KPIResultOmit<ExtArgs> | null
  /**
   * The data used to update KPIResults.
   */
  data: Prisma.XOR<Prisma.KPIResultUpdateManyMutationInput, Prisma.KPIResultUncheckedUpdateManyInput>
  /**
   * Filter which KPIResults to update
   */
  where?: Prisma.KPIResultWhereInput
  /**
   * Limit how many KPIResults to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KPIResultIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * KPIResult upsert
 */
export type KPIResultUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KPIResult
   */
  select?: Prisma.KPIResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KPIResult
   */
  omit?: Prisma.KPIResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KPIResultInclude<ExtArgs> | null
  /**
   * The filter to search for the KPIResult to update in case it exists.
   */
  where: Prisma.KPIResultWhereUniqueInput
  /**
   * In case the KPIResult found by the `where` argument doesn't exist, create a new KPIResult with this data.
   */
  create: Prisma.XOR<Prisma.KPIResultCreateInput, Prisma.KPIResultUncheckedCreateInput>
  /**
   * In case the KPIResult was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.KPIResultUpdateInput, Prisma.KPIResultUncheckedUpdateInput>
}

/**
 * KPIResult delete
 */
export type KPIResultDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KPIResult
   */
  select?: Prisma.KPIResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KPIResult
   */
  omit?: Prisma.KPIResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KPIResultInclude<ExtArgs> | null
  /**
   * Filter which KPIResult to delete.
   */
  where: Prisma.KPIResultWhereUniqueInput
}

/**
 * KPIResult deleteMany
 */
export type KPIResultDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KPIResults to delete
   */
  where?: Prisma.KPIResultWhereInput
  /**
   * Limit how many KPIResults to delete.
   */
  limit?: number
}

/**
 * KPIResult without action
 */
export type KPIResultDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KPIResult
   */
  select?: Prisma.KPIResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KPIResult
   */
  omit?: Prisma.KPIResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KPIResultInclude<ExtArgs> | null
}
