
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Submission` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Submission
 * 
 */
export type SubmissionModel = runtime.Types.Result.DefaultSelection<Prisma.$SubmissionPayload>

export type AggregateSubmission = {
  _count: SubmissionCountAggregateOutputType | null
  _avg: SubmissionAvgAggregateOutputType | null
  _sum: SubmissionSumAggregateOutputType | null
  _min: SubmissionMinAggregateOutputType | null
  _max: SubmissionMaxAggregateOutputType | null
}

export type SubmissionAvgAggregateOutputType = {
  amount: number | null
}

export type SubmissionSumAggregateOutputType = {
  amount: number | null
}

export type SubmissionMinAggregateOutputType = {
  id: string | null
  taskId: string | null
  builderId: string | null
  workSummary: string | null
  status: string | null
  reviewNotes: string | null
  amount: number | null
  reviewedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SubmissionMaxAggregateOutputType = {
  id: string | null
  taskId: string | null
  builderId: string | null
  workSummary: string | null
  status: string | null
  reviewNotes: string | null
  amount: number | null
  reviewedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SubmissionCountAggregateOutputType = {
  id: number
  taskId: number
  builderId: number
  workSummary: number
  status: number
  reviewNotes: number
  amount: number
  reviewedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SubmissionAvgAggregateInputType = {
  amount?: true
}

export type SubmissionSumAggregateInputType = {
  amount?: true
}

export type SubmissionMinAggregateInputType = {
  id?: true
  taskId?: true
  builderId?: true
  workSummary?: true
  status?: true
  reviewNotes?: true
  amount?: true
  reviewedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type SubmissionMaxAggregateInputType = {
  id?: true
  taskId?: true
  builderId?: true
  workSummary?: true
  status?: true
  reviewNotes?: true
  amount?: true
  reviewedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type SubmissionCountAggregateInputType = {
  id?: true
  taskId?: true
  builderId?: true
  workSummary?: true
  status?: true
  reviewNotes?: true
  amount?: true
  reviewedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SubmissionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Submission to aggregate.
   */
  where?: Prisma.SubmissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Submissions to fetch.
   */
  orderBy?: Prisma.SubmissionOrderByWithRelationInput | Prisma.SubmissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SubmissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Submissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Submissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Submissions
  **/
  _count?: true | SubmissionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SubmissionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SubmissionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SubmissionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SubmissionMaxAggregateInputType
}

export type GetSubmissionAggregateType<T extends SubmissionAggregateArgs> = {
      [P in keyof T & keyof AggregateSubmission]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSubmission[P]>
    : Prisma.GetScalarType<T[P], AggregateSubmission[P]>
}




export type SubmissionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SubmissionWhereInput
  orderBy?: Prisma.SubmissionOrderByWithAggregationInput | Prisma.SubmissionOrderByWithAggregationInput[]
  by: Prisma.SubmissionScalarFieldEnum[] | Prisma.SubmissionScalarFieldEnum
  having?: Prisma.SubmissionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SubmissionCountAggregateInputType | true
  _avg?: SubmissionAvgAggregateInputType
  _sum?: SubmissionSumAggregateInputType
  _min?: SubmissionMinAggregateInputType
  _max?: SubmissionMaxAggregateInputType
}

export type SubmissionGroupByOutputType = {
  id: string
  taskId: string
  builderId: string
  workSummary: string
  status: string
  reviewNotes: string | null
  amount: number | null
  reviewedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: SubmissionCountAggregateOutputType | null
  _avg: SubmissionAvgAggregateOutputType | null
  _sum: SubmissionSumAggregateOutputType | null
  _min: SubmissionMinAggregateOutputType | null
  _max: SubmissionMaxAggregateOutputType | null
}

type GetSubmissionGroupByPayload<T extends SubmissionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SubmissionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SubmissionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SubmissionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SubmissionGroupByOutputType[P]>
      }
    >
  >



export type SubmissionWhereInput = {
  AND?: Prisma.SubmissionWhereInput | Prisma.SubmissionWhereInput[]
  OR?: Prisma.SubmissionWhereInput[]
  NOT?: Prisma.SubmissionWhereInput | Prisma.SubmissionWhereInput[]
  id?: Prisma.StringFilter<"Submission"> | string
  taskId?: Prisma.StringFilter<"Submission"> | string
  builderId?: Prisma.StringFilter<"Submission"> | string
  workSummary?: Prisma.StringFilter<"Submission"> | string
  status?: Prisma.StringFilter<"Submission"> | string
  reviewNotes?: Prisma.StringNullableFilter<"Submission"> | string | null
  amount?: Prisma.FloatNullableFilter<"Submission"> | number | null
  reviewedAt?: Prisma.DateTimeNullableFilter<"Submission"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Submission"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Submission"> | Date | string
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
  builder?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  kpiResults?: Prisma.KPIResultListRelationFilter
  supportingFiles?: Prisma.SupportingFileListRelationFilter
}

export type SubmissionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  builderId?: Prisma.SortOrder
  workSummary?: Prisma.SortOrder
  status?: Prisma.SortOrder
  reviewNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  amount?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  task?: Prisma.TaskOrderByWithRelationInput
  builder?: Prisma.UserOrderByWithRelationInput
  kpiResults?: Prisma.KPIResultOrderByRelationAggregateInput
  supportingFiles?: Prisma.SupportingFileOrderByRelationAggregateInput
}

export type SubmissionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SubmissionWhereInput | Prisma.SubmissionWhereInput[]
  OR?: Prisma.SubmissionWhereInput[]
  NOT?: Prisma.SubmissionWhereInput | Prisma.SubmissionWhereInput[]
  taskId?: Prisma.StringFilter<"Submission"> | string
  builderId?: Prisma.StringFilter<"Submission"> | string
  workSummary?: Prisma.StringFilter<"Submission"> | string
  status?: Prisma.StringFilter<"Submission"> | string
  reviewNotes?: Prisma.StringNullableFilter<"Submission"> | string | null
  amount?: Prisma.FloatNullableFilter<"Submission"> | number | null
  reviewedAt?: Prisma.DateTimeNullableFilter<"Submission"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Submission"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Submission"> | Date | string
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
  builder?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  kpiResults?: Prisma.KPIResultListRelationFilter
  supportingFiles?: Prisma.SupportingFileListRelationFilter
}, "id">

export type SubmissionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  builderId?: Prisma.SortOrder
  workSummary?: Prisma.SortOrder
  status?: Prisma.SortOrder
  reviewNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  amount?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SubmissionCountOrderByAggregateInput
  _avg?: Prisma.SubmissionAvgOrderByAggregateInput
  _max?: Prisma.SubmissionMaxOrderByAggregateInput
  _min?: Prisma.SubmissionMinOrderByAggregateInput
  _sum?: Prisma.SubmissionSumOrderByAggregateInput
}

export type SubmissionScalarWhereWithAggregatesInput = {
  AND?: Prisma.SubmissionScalarWhereWithAggregatesInput | Prisma.SubmissionScalarWhereWithAggregatesInput[]
  OR?: Prisma.SubmissionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SubmissionScalarWhereWithAggregatesInput | Prisma.SubmissionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Submission"> | string
  taskId?: Prisma.StringWithAggregatesFilter<"Submission"> | string
  builderId?: Prisma.StringWithAggregatesFilter<"Submission"> | string
  workSummary?: Prisma.StringWithAggregatesFilter<"Submission"> | string
  status?: Prisma.StringWithAggregatesFilter<"Submission"> | string
  reviewNotes?: Prisma.StringNullableWithAggregatesFilter<"Submission"> | string | null
  amount?: Prisma.FloatNullableWithAggregatesFilter<"Submission"> | number | null
  reviewedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Submission"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Submission"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Submission"> | Date | string
}

export type SubmissionCreateInput = {
  id?: string
  workSummary: string
  status?: string
  reviewNotes?: string | null
  amount?: number | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  task: Prisma.TaskCreateNestedOneWithoutSubmissionsInput
  builder: Prisma.UserCreateNestedOneWithoutSubmissionsInput
  kpiResults?: Prisma.KPIResultCreateNestedManyWithoutSubmissionInput
  supportingFiles?: Prisma.SupportingFileCreateNestedManyWithoutSubmissionInput
}

export type SubmissionUncheckedCreateInput = {
  id?: string
  taskId: string
  builderId: string
  workSummary: string
  status?: string
  reviewNotes?: string | null
  amount?: number | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  kpiResults?: Prisma.KPIResultUncheckedCreateNestedManyWithoutSubmissionInput
  supportingFiles?: Prisma.SupportingFileUncheckedCreateNestedManyWithoutSubmissionInput
}

export type SubmissionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workSummary?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  reviewNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  task?: Prisma.TaskUpdateOneRequiredWithoutSubmissionsNestedInput
  builder?: Prisma.UserUpdateOneRequiredWithoutSubmissionsNestedInput
  kpiResults?: Prisma.KPIResultUpdateManyWithoutSubmissionNestedInput
  supportingFiles?: Prisma.SupportingFileUpdateManyWithoutSubmissionNestedInput
}

export type SubmissionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  builderId?: Prisma.StringFieldUpdateOperationsInput | string
  workSummary?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  reviewNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kpiResults?: Prisma.KPIResultUncheckedUpdateManyWithoutSubmissionNestedInput
  supportingFiles?: Prisma.SupportingFileUncheckedUpdateManyWithoutSubmissionNestedInput
}

export type SubmissionCreateManyInput = {
  id?: string
  taskId: string
  builderId: string
  workSummary: string
  status?: string
  reviewNotes?: string | null
  amount?: number | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SubmissionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workSummary?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  reviewNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubmissionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  builderId?: Prisma.StringFieldUpdateOperationsInput | string
  workSummary?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  reviewNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubmissionListRelationFilter = {
  every?: Prisma.SubmissionWhereInput
  some?: Prisma.SubmissionWhereInput
  none?: Prisma.SubmissionWhereInput
}

export type SubmissionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SubmissionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  builderId?: Prisma.SortOrder
  workSummary?: Prisma.SortOrder
  status?: Prisma.SortOrder
  reviewNotes?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SubmissionAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type SubmissionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  builderId?: Prisma.SortOrder
  workSummary?: Prisma.SortOrder
  status?: Prisma.SortOrder
  reviewNotes?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SubmissionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  builderId?: Prisma.SortOrder
  workSummary?: Prisma.SortOrder
  status?: Prisma.SortOrder
  reviewNotes?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SubmissionSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type SubmissionScalarRelationFilter = {
  is?: Prisma.SubmissionWhereInput
  isNot?: Prisma.SubmissionWhereInput
}

export type SubmissionCreateNestedManyWithoutBuilderInput = {
  create?: Prisma.XOR<Prisma.SubmissionCreateWithoutBuilderInput, Prisma.SubmissionUncheckedCreateWithoutBuilderInput> | Prisma.SubmissionCreateWithoutBuilderInput[] | Prisma.SubmissionUncheckedCreateWithoutBuilderInput[]
  connectOrCreate?: Prisma.SubmissionCreateOrConnectWithoutBuilderInput | Prisma.SubmissionCreateOrConnectWithoutBuilderInput[]
  createMany?: Prisma.SubmissionCreateManyBuilderInputEnvelope
  connect?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
}

export type SubmissionUncheckedCreateNestedManyWithoutBuilderInput = {
  create?: Prisma.XOR<Prisma.SubmissionCreateWithoutBuilderInput, Prisma.SubmissionUncheckedCreateWithoutBuilderInput> | Prisma.SubmissionCreateWithoutBuilderInput[] | Prisma.SubmissionUncheckedCreateWithoutBuilderInput[]
  connectOrCreate?: Prisma.SubmissionCreateOrConnectWithoutBuilderInput | Prisma.SubmissionCreateOrConnectWithoutBuilderInput[]
  createMany?: Prisma.SubmissionCreateManyBuilderInputEnvelope
  connect?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
}

export type SubmissionUpdateManyWithoutBuilderNestedInput = {
  create?: Prisma.XOR<Prisma.SubmissionCreateWithoutBuilderInput, Prisma.SubmissionUncheckedCreateWithoutBuilderInput> | Prisma.SubmissionCreateWithoutBuilderInput[] | Prisma.SubmissionUncheckedCreateWithoutBuilderInput[]
  connectOrCreate?: Prisma.SubmissionCreateOrConnectWithoutBuilderInput | Prisma.SubmissionCreateOrConnectWithoutBuilderInput[]
  upsert?: Prisma.SubmissionUpsertWithWhereUniqueWithoutBuilderInput | Prisma.SubmissionUpsertWithWhereUniqueWithoutBuilderInput[]
  createMany?: Prisma.SubmissionCreateManyBuilderInputEnvelope
  set?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  disconnect?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  delete?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  connect?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  update?: Prisma.SubmissionUpdateWithWhereUniqueWithoutBuilderInput | Prisma.SubmissionUpdateWithWhereUniqueWithoutBuilderInput[]
  updateMany?: Prisma.SubmissionUpdateManyWithWhereWithoutBuilderInput | Prisma.SubmissionUpdateManyWithWhereWithoutBuilderInput[]
  deleteMany?: Prisma.SubmissionScalarWhereInput | Prisma.SubmissionScalarWhereInput[]
}

export type SubmissionUncheckedUpdateManyWithoutBuilderNestedInput = {
  create?: Prisma.XOR<Prisma.SubmissionCreateWithoutBuilderInput, Prisma.SubmissionUncheckedCreateWithoutBuilderInput> | Prisma.SubmissionCreateWithoutBuilderInput[] | Prisma.SubmissionUncheckedCreateWithoutBuilderInput[]
  connectOrCreate?: Prisma.SubmissionCreateOrConnectWithoutBuilderInput | Prisma.SubmissionCreateOrConnectWithoutBuilderInput[]
  upsert?: Prisma.SubmissionUpsertWithWhereUniqueWithoutBuilderInput | Prisma.SubmissionUpsertWithWhereUniqueWithoutBuilderInput[]
  createMany?: Prisma.SubmissionCreateManyBuilderInputEnvelope
  set?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  disconnect?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  delete?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  connect?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  update?: Prisma.SubmissionUpdateWithWhereUniqueWithoutBuilderInput | Prisma.SubmissionUpdateWithWhereUniqueWithoutBuilderInput[]
  updateMany?: Prisma.SubmissionUpdateManyWithWhereWithoutBuilderInput | Prisma.SubmissionUpdateManyWithWhereWithoutBuilderInput[]
  deleteMany?: Prisma.SubmissionScalarWhereInput | Prisma.SubmissionScalarWhereInput[]
}

export type SubmissionCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.SubmissionCreateWithoutTaskInput, Prisma.SubmissionUncheckedCreateWithoutTaskInput> | Prisma.SubmissionCreateWithoutTaskInput[] | Prisma.SubmissionUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.SubmissionCreateOrConnectWithoutTaskInput | Prisma.SubmissionCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.SubmissionCreateManyTaskInputEnvelope
  connect?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
}

export type SubmissionUncheckedCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.SubmissionCreateWithoutTaskInput, Prisma.SubmissionUncheckedCreateWithoutTaskInput> | Prisma.SubmissionCreateWithoutTaskInput[] | Prisma.SubmissionUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.SubmissionCreateOrConnectWithoutTaskInput | Prisma.SubmissionCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.SubmissionCreateManyTaskInputEnvelope
  connect?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
}

export type SubmissionUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.SubmissionCreateWithoutTaskInput, Prisma.SubmissionUncheckedCreateWithoutTaskInput> | Prisma.SubmissionCreateWithoutTaskInput[] | Prisma.SubmissionUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.SubmissionCreateOrConnectWithoutTaskInput | Prisma.SubmissionCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.SubmissionUpsertWithWhereUniqueWithoutTaskInput | Prisma.SubmissionUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.SubmissionCreateManyTaskInputEnvelope
  set?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  disconnect?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  delete?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  connect?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  update?: Prisma.SubmissionUpdateWithWhereUniqueWithoutTaskInput | Prisma.SubmissionUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.SubmissionUpdateManyWithWhereWithoutTaskInput | Prisma.SubmissionUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.SubmissionScalarWhereInput | Prisma.SubmissionScalarWhereInput[]
}

export type SubmissionUncheckedUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.SubmissionCreateWithoutTaskInput, Prisma.SubmissionUncheckedCreateWithoutTaskInput> | Prisma.SubmissionCreateWithoutTaskInput[] | Prisma.SubmissionUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.SubmissionCreateOrConnectWithoutTaskInput | Prisma.SubmissionCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.SubmissionUpsertWithWhereUniqueWithoutTaskInput | Prisma.SubmissionUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.SubmissionCreateManyTaskInputEnvelope
  set?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  disconnect?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  delete?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  connect?: Prisma.SubmissionWhereUniqueInput | Prisma.SubmissionWhereUniqueInput[]
  update?: Prisma.SubmissionUpdateWithWhereUniqueWithoutTaskInput | Prisma.SubmissionUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.SubmissionUpdateManyWithWhereWithoutTaskInput | Prisma.SubmissionUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.SubmissionScalarWhereInput | Prisma.SubmissionScalarWhereInput[]
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type SubmissionCreateNestedOneWithoutKpiResultsInput = {
  create?: Prisma.XOR<Prisma.SubmissionCreateWithoutKpiResultsInput, Prisma.SubmissionUncheckedCreateWithoutKpiResultsInput>
  connectOrCreate?: Prisma.SubmissionCreateOrConnectWithoutKpiResultsInput
  connect?: Prisma.SubmissionWhereUniqueInput
}

export type SubmissionUpdateOneRequiredWithoutKpiResultsNestedInput = {
  create?: Prisma.XOR<Prisma.SubmissionCreateWithoutKpiResultsInput, Prisma.SubmissionUncheckedCreateWithoutKpiResultsInput>
  connectOrCreate?: Prisma.SubmissionCreateOrConnectWithoutKpiResultsInput
  upsert?: Prisma.SubmissionUpsertWithoutKpiResultsInput
  connect?: Prisma.SubmissionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SubmissionUpdateToOneWithWhereWithoutKpiResultsInput, Prisma.SubmissionUpdateWithoutKpiResultsInput>, Prisma.SubmissionUncheckedUpdateWithoutKpiResultsInput>
}

export type SubmissionCreateNestedOneWithoutSupportingFilesInput = {
  create?: Prisma.XOR<Prisma.SubmissionCreateWithoutSupportingFilesInput, Prisma.SubmissionUncheckedCreateWithoutSupportingFilesInput>
  connectOrCreate?: Prisma.SubmissionCreateOrConnectWithoutSupportingFilesInput
  connect?: Prisma.SubmissionWhereUniqueInput
}

export type SubmissionUpdateOneRequiredWithoutSupportingFilesNestedInput = {
  create?: Prisma.XOR<Prisma.SubmissionCreateWithoutSupportingFilesInput, Prisma.SubmissionUncheckedCreateWithoutSupportingFilesInput>
  connectOrCreate?: Prisma.SubmissionCreateOrConnectWithoutSupportingFilesInput
  upsert?: Prisma.SubmissionUpsertWithoutSupportingFilesInput
  connect?: Prisma.SubmissionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SubmissionUpdateToOneWithWhereWithoutSupportingFilesInput, Prisma.SubmissionUpdateWithoutSupportingFilesInput>, Prisma.SubmissionUncheckedUpdateWithoutSupportingFilesInput>
}

export type SubmissionCreateWithoutBuilderInput = {
  id?: string
  workSummary: string
  status?: string
  reviewNotes?: string | null
  amount?: number | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  task: Prisma.TaskCreateNestedOneWithoutSubmissionsInput
  kpiResults?: Prisma.KPIResultCreateNestedManyWithoutSubmissionInput
  supportingFiles?: Prisma.SupportingFileCreateNestedManyWithoutSubmissionInput
}

export type SubmissionUncheckedCreateWithoutBuilderInput = {
  id?: string
  taskId: string
  workSummary: string
  status?: string
  reviewNotes?: string | null
  amount?: number | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  kpiResults?: Prisma.KPIResultUncheckedCreateNestedManyWithoutSubmissionInput
  supportingFiles?: Prisma.SupportingFileUncheckedCreateNestedManyWithoutSubmissionInput
}

export type SubmissionCreateOrConnectWithoutBuilderInput = {
  where: Prisma.SubmissionWhereUniqueInput
  create: Prisma.XOR<Prisma.SubmissionCreateWithoutBuilderInput, Prisma.SubmissionUncheckedCreateWithoutBuilderInput>
}

export type SubmissionCreateManyBuilderInputEnvelope = {
  data: Prisma.SubmissionCreateManyBuilderInput | Prisma.SubmissionCreateManyBuilderInput[]
  skipDuplicates?: boolean
}

export type SubmissionUpsertWithWhereUniqueWithoutBuilderInput = {
  where: Prisma.SubmissionWhereUniqueInput
  update: Prisma.XOR<Prisma.SubmissionUpdateWithoutBuilderInput, Prisma.SubmissionUncheckedUpdateWithoutBuilderInput>
  create: Prisma.XOR<Prisma.SubmissionCreateWithoutBuilderInput, Prisma.SubmissionUncheckedCreateWithoutBuilderInput>
}

export type SubmissionUpdateWithWhereUniqueWithoutBuilderInput = {
  where: Prisma.SubmissionWhereUniqueInput
  data: Prisma.XOR<Prisma.SubmissionUpdateWithoutBuilderInput, Prisma.SubmissionUncheckedUpdateWithoutBuilderInput>
}

export type SubmissionUpdateManyWithWhereWithoutBuilderInput = {
  where: Prisma.SubmissionScalarWhereInput
  data: Prisma.XOR<Prisma.SubmissionUpdateManyMutationInput, Prisma.SubmissionUncheckedUpdateManyWithoutBuilderInput>
}

export type SubmissionScalarWhereInput = {
  AND?: Prisma.SubmissionScalarWhereInput | Prisma.SubmissionScalarWhereInput[]
  OR?: Prisma.SubmissionScalarWhereInput[]
  NOT?: Prisma.SubmissionScalarWhereInput | Prisma.SubmissionScalarWhereInput[]
  id?: Prisma.StringFilter<"Submission"> | string
  taskId?: Prisma.StringFilter<"Submission"> | string
  builderId?: Prisma.StringFilter<"Submission"> | string
  workSummary?: Prisma.StringFilter<"Submission"> | string
  status?: Prisma.StringFilter<"Submission"> | string
  reviewNotes?: Prisma.StringNullableFilter<"Submission"> | string | null
  amount?: Prisma.FloatNullableFilter<"Submission"> | number | null
  reviewedAt?: Prisma.DateTimeNullableFilter<"Submission"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Submission"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Submission"> | Date | string
}

export type SubmissionCreateWithoutTaskInput = {
  id?: string
  workSummary: string
  status?: string
  reviewNotes?: string | null
  amount?: number | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  builder: Prisma.UserCreateNestedOneWithoutSubmissionsInput
  kpiResults?: Prisma.KPIResultCreateNestedManyWithoutSubmissionInput
  supportingFiles?: Prisma.SupportingFileCreateNestedManyWithoutSubmissionInput
}

export type SubmissionUncheckedCreateWithoutTaskInput = {
  id?: string
  builderId: string
  workSummary: string
  status?: string
  reviewNotes?: string | null
  amount?: number | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  kpiResults?: Prisma.KPIResultUncheckedCreateNestedManyWithoutSubmissionInput
  supportingFiles?: Prisma.SupportingFileUncheckedCreateNestedManyWithoutSubmissionInput
}

export type SubmissionCreateOrConnectWithoutTaskInput = {
  where: Prisma.SubmissionWhereUniqueInput
  create: Prisma.XOR<Prisma.SubmissionCreateWithoutTaskInput, Prisma.SubmissionUncheckedCreateWithoutTaskInput>
}

export type SubmissionCreateManyTaskInputEnvelope = {
  data: Prisma.SubmissionCreateManyTaskInput | Prisma.SubmissionCreateManyTaskInput[]
  skipDuplicates?: boolean
}

export type SubmissionUpsertWithWhereUniqueWithoutTaskInput = {
  where: Prisma.SubmissionWhereUniqueInput
  update: Prisma.XOR<Prisma.SubmissionUpdateWithoutTaskInput, Prisma.SubmissionUncheckedUpdateWithoutTaskInput>
  create: Prisma.XOR<Prisma.SubmissionCreateWithoutTaskInput, Prisma.SubmissionUncheckedCreateWithoutTaskInput>
}

export type SubmissionUpdateWithWhereUniqueWithoutTaskInput = {
  where: Prisma.SubmissionWhereUniqueInput
  data: Prisma.XOR<Prisma.SubmissionUpdateWithoutTaskInput, Prisma.SubmissionUncheckedUpdateWithoutTaskInput>
}

export type SubmissionUpdateManyWithWhereWithoutTaskInput = {
  where: Prisma.SubmissionScalarWhereInput
  data: Prisma.XOR<Prisma.SubmissionUpdateManyMutationInput, Prisma.SubmissionUncheckedUpdateManyWithoutTaskInput>
}

export type SubmissionCreateWithoutKpiResultsInput = {
  id?: string
  workSummary: string
  status?: string
  reviewNotes?: string | null
  amount?: number | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  task: Prisma.TaskCreateNestedOneWithoutSubmissionsInput
  builder: Prisma.UserCreateNestedOneWithoutSubmissionsInput
  supportingFiles?: Prisma.SupportingFileCreateNestedManyWithoutSubmissionInput
}

export type SubmissionUncheckedCreateWithoutKpiResultsInput = {
  id?: string
  taskId: string
  builderId: string
  workSummary: string
  status?: string
  reviewNotes?: string | null
  amount?: number | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  supportingFiles?: Prisma.SupportingFileUncheckedCreateNestedManyWithoutSubmissionInput
}

export type SubmissionCreateOrConnectWithoutKpiResultsInput = {
  where: Prisma.SubmissionWhereUniqueInput
  create: Prisma.XOR<Prisma.SubmissionCreateWithoutKpiResultsInput, Prisma.SubmissionUncheckedCreateWithoutKpiResultsInput>
}

export type SubmissionUpsertWithoutKpiResultsInput = {
  update: Prisma.XOR<Prisma.SubmissionUpdateWithoutKpiResultsInput, Prisma.SubmissionUncheckedUpdateWithoutKpiResultsInput>
  create: Prisma.XOR<Prisma.SubmissionCreateWithoutKpiResultsInput, Prisma.SubmissionUncheckedCreateWithoutKpiResultsInput>
  where?: Prisma.SubmissionWhereInput
}

export type SubmissionUpdateToOneWithWhereWithoutKpiResultsInput = {
  where?: Prisma.SubmissionWhereInput
  data: Prisma.XOR<Prisma.SubmissionUpdateWithoutKpiResultsInput, Prisma.SubmissionUncheckedUpdateWithoutKpiResultsInput>
}

export type SubmissionUpdateWithoutKpiResultsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workSummary?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  reviewNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  task?: Prisma.TaskUpdateOneRequiredWithoutSubmissionsNestedInput
  builder?: Prisma.UserUpdateOneRequiredWithoutSubmissionsNestedInput
  supportingFiles?: Prisma.SupportingFileUpdateManyWithoutSubmissionNestedInput
}

export type SubmissionUncheckedUpdateWithoutKpiResultsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  builderId?: Prisma.StringFieldUpdateOperationsInput | string
  workSummary?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  reviewNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  supportingFiles?: Prisma.SupportingFileUncheckedUpdateManyWithoutSubmissionNestedInput
}

export type SubmissionCreateWithoutSupportingFilesInput = {
  id?: string
  workSummary: string
  status?: string
  reviewNotes?: string | null
  amount?: number | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  task: Prisma.TaskCreateNestedOneWithoutSubmissionsInput
  builder: Prisma.UserCreateNestedOneWithoutSubmissionsInput
  kpiResults?: Prisma.KPIResultCreateNestedManyWithoutSubmissionInput
}

export type SubmissionUncheckedCreateWithoutSupportingFilesInput = {
  id?: string
  taskId: string
  builderId: string
  workSummary: string
  status?: string
  reviewNotes?: string | null
  amount?: number | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  kpiResults?: Prisma.KPIResultUncheckedCreateNestedManyWithoutSubmissionInput
}

export type SubmissionCreateOrConnectWithoutSupportingFilesInput = {
  where: Prisma.SubmissionWhereUniqueInput
  create: Prisma.XOR<Prisma.SubmissionCreateWithoutSupportingFilesInput, Prisma.SubmissionUncheckedCreateWithoutSupportingFilesInput>
}

export type SubmissionUpsertWithoutSupportingFilesInput = {
  update: Prisma.XOR<Prisma.SubmissionUpdateWithoutSupportingFilesInput, Prisma.SubmissionUncheckedUpdateWithoutSupportingFilesInput>
  create: Prisma.XOR<Prisma.SubmissionCreateWithoutSupportingFilesInput, Prisma.SubmissionUncheckedCreateWithoutSupportingFilesInput>
  where?: Prisma.SubmissionWhereInput
}

export type SubmissionUpdateToOneWithWhereWithoutSupportingFilesInput = {
  where?: Prisma.SubmissionWhereInput
  data: Prisma.XOR<Prisma.SubmissionUpdateWithoutSupportingFilesInput, Prisma.SubmissionUncheckedUpdateWithoutSupportingFilesInput>
}

export type SubmissionUpdateWithoutSupportingFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workSummary?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  reviewNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  task?: Prisma.TaskUpdateOneRequiredWithoutSubmissionsNestedInput
  builder?: Prisma.UserUpdateOneRequiredWithoutSubmissionsNestedInput
  kpiResults?: Prisma.KPIResultUpdateManyWithoutSubmissionNestedInput
}

export type SubmissionUncheckedUpdateWithoutSupportingFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  builderId?: Prisma.StringFieldUpdateOperationsInput | string
  workSummary?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  reviewNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kpiResults?: Prisma.KPIResultUncheckedUpdateManyWithoutSubmissionNestedInput
}

export type SubmissionCreateManyBuilderInput = {
  id?: string
  taskId: string
  workSummary: string
  status?: string
  reviewNotes?: string | null
  amount?: number | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SubmissionUpdateWithoutBuilderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workSummary?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  reviewNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  task?: Prisma.TaskUpdateOneRequiredWithoutSubmissionsNestedInput
  kpiResults?: Prisma.KPIResultUpdateManyWithoutSubmissionNestedInput
  supportingFiles?: Prisma.SupportingFileUpdateManyWithoutSubmissionNestedInput
}

export type SubmissionUncheckedUpdateWithoutBuilderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  workSummary?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  reviewNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kpiResults?: Prisma.KPIResultUncheckedUpdateManyWithoutSubmissionNestedInput
  supportingFiles?: Prisma.SupportingFileUncheckedUpdateManyWithoutSubmissionNestedInput
}

export type SubmissionUncheckedUpdateManyWithoutBuilderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  workSummary?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  reviewNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SubmissionCreateManyTaskInput = {
  id?: string
  builderId: string
  workSummary: string
  status?: string
  reviewNotes?: string | null
  amount?: number | null
  reviewedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SubmissionUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workSummary?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  reviewNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  builder?: Prisma.UserUpdateOneRequiredWithoutSubmissionsNestedInput
  kpiResults?: Prisma.KPIResultUpdateManyWithoutSubmissionNestedInput
  supportingFiles?: Prisma.SupportingFileUpdateManyWithoutSubmissionNestedInput
}

export type SubmissionUncheckedUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  builderId?: Prisma.StringFieldUpdateOperationsInput | string
  workSummary?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  reviewNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  kpiResults?: Prisma.KPIResultUncheckedUpdateManyWithoutSubmissionNestedInput
  supportingFiles?: Prisma.SupportingFileUncheckedUpdateManyWithoutSubmissionNestedInput
}

export type SubmissionUncheckedUpdateManyWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  builderId?: Prisma.StringFieldUpdateOperationsInput | string
  workSummary?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  reviewNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type SubmissionCountOutputType
 */

export type SubmissionCountOutputType = {
  kpiResults: number
  supportingFiles: number
}

export type SubmissionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kpiResults?: boolean | SubmissionCountOutputTypeCountKpiResultsArgs
  supportingFiles?: boolean | SubmissionCountOutputTypeCountSupportingFilesArgs
}

/**
 * SubmissionCountOutputType without action
 */
export type SubmissionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubmissionCountOutputType
   */
  select?: Prisma.SubmissionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SubmissionCountOutputType without action
 */
export type SubmissionCountOutputTypeCountKpiResultsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KPIResultWhereInput
}

/**
 * SubmissionCountOutputType without action
 */
export type SubmissionCountOutputTypeCountSupportingFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SupportingFileWhereInput
}


export type SubmissionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  taskId?: boolean
  builderId?: boolean
  workSummary?: boolean
  status?: boolean
  reviewNotes?: boolean
  amount?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  builder?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  kpiResults?: boolean | Prisma.Submission$kpiResultsArgs<ExtArgs>
  supportingFiles?: boolean | Prisma.Submission$supportingFilesArgs<ExtArgs>
  _count?: boolean | Prisma.SubmissionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["submission"]>

export type SubmissionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  taskId?: boolean
  builderId?: boolean
  workSummary?: boolean
  status?: boolean
  reviewNotes?: boolean
  amount?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  builder?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["submission"]>

export type SubmissionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  taskId?: boolean
  builderId?: boolean
  workSummary?: boolean
  status?: boolean
  reviewNotes?: boolean
  amount?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  builder?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["submission"]>

export type SubmissionSelectScalar = {
  id?: boolean
  taskId?: boolean
  builderId?: boolean
  workSummary?: boolean
  status?: boolean
  reviewNotes?: boolean
  amount?: boolean
  reviewedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SubmissionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "taskId" | "builderId" | "workSummary" | "status" | "reviewNotes" | "amount" | "reviewedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["submission"]>
export type SubmissionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  builder?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  kpiResults?: boolean | Prisma.Submission$kpiResultsArgs<ExtArgs>
  supportingFiles?: boolean | Prisma.Submission$supportingFilesArgs<ExtArgs>
  _count?: boolean | Prisma.SubmissionCountOutputTypeDefaultArgs<ExtArgs>
}
export type SubmissionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  builder?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SubmissionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  builder?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $SubmissionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Submission"
  objects: {
    task: Prisma.$TaskPayload<ExtArgs>
    builder: Prisma.$UserPayload<ExtArgs>
    kpiResults: Prisma.$KPIResultPayload<ExtArgs>[]
    supportingFiles: Prisma.$SupportingFilePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    taskId: string
    builderId: string
    workSummary: string
    status: string
    reviewNotes: string | null
    amount: number | null
    reviewedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["submission"]>
  composites: {}
}

export type SubmissionGetPayload<S extends boolean | null | undefined | SubmissionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SubmissionPayload, S>

export type SubmissionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SubmissionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SubmissionCountAggregateInputType | true
  }

export interface SubmissionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Submission'], meta: { name: 'Submission' } }
  /**
   * Find zero or one Submission that matches the filter.
   * @param {SubmissionFindUniqueArgs} args - Arguments to find a Submission
   * @example
   * // Get one Submission
   * const submission = await prisma.submission.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SubmissionFindUniqueArgs>(args: Prisma.SelectSubset<T, SubmissionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SubmissionClient<runtime.Types.Result.GetResult<Prisma.$SubmissionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Submission that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SubmissionFindUniqueOrThrowArgs} args - Arguments to find a Submission
   * @example
   * // Get one Submission
   * const submission = await prisma.submission.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SubmissionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SubmissionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubmissionClient<runtime.Types.Result.GetResult<Prisma.$SubmissionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Submission that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionFindFirstArgs} args - Arguments to find a Submission
   * @example
   * // Get one Submission
   * const submission = await prisma.submission.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SubmissionFindFirstArgs>(args?: Prisma.SelectSubset<T, SubmissionFindFirstArgs<ExtArgs>>): Prisma.Prisma__SubmissionClient<runtime.Types.Result.GetResult<Prisma.$SubmissionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Submission that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionFindFirstOrThrowArgs} args - Arguments to find a Submission
   * @example
   * // Get one Submission
   * const submission = await prisma.submission.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SubmissionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SubmissionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SubmissionClient<runtime.Types.Result.GetResult<Prisma.$SubmissionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Submissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Submissions
   * const submissions = await prisma.submission.findMany()
   * 
   * // Get first 10 Submissions
   * const submissions = await prisma.submission.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const submissionWithIdOnly = await prisma.submission.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SubmissionFindManyArgs>(args?: Prisma.SelectSubset<T, SubmissionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubmissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Submission.
   * @param {SubmissionCreateArgs} args - Arguments to create a Submission.
   * @example
   * // Create one Submission
   * const Submission = await prisma.submission.create({
   *   data: {
   *     // ... data to create a Submission
   *   }
   * })
   * 
   */
  create<T extends SubmissionCreateArgs>(args: Prisma.SelectSubset<T, SubmissionCreateArgs<ExtArgs>>): Prisma.Prisma__SubmissionClient<runtime.Types.Result.GetResult<Prisma.$SubmissionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Submissions.
   * @param {SubmissionCreateManyArgs} args - Arguments to create many Submissions.
   * @example
   * // Create many Submissions
   * const submission = await prisma.submission.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SubmissionCreateManyArgs>(args?: Prisma.SelectSubset<T, SubmissionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Submissions and returns the data saved in the database.
   * @param {SubmissionCreateManyAndReturnArgs} args - Arguments to create many Submissions.
   * @example
   * // Create many Submissions
   * const submission = await prisma.submission.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Submissions and only return the `id`
   * const submissionWithIdOnly = await prisma.submission.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SubmissionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SubmissionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubmissionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Submission.
   * @param {SubmissionDeleteArgs} args - Arguments to delete one Submission.
   * @example
   * // Delete one Submission
   * const Submission = await prisma.submission.delete({
   *   where: {
   *     // ... filter to delete one Submission
   *   }
   * })
   * 
   */
  delete<T extends SubmissionDeleteArgs>(args: Prisma.SelectSubset<T, SubmissionDeleteArgs<ExtArgs>>): Prisma.Prisma__SubmissionClient<runtime.Types.Result.GetResult<Prisma.$SubmissionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Submission.
   * @param {SubmissionUpdateArgs} args - Arguments to update one Submission.
   * @example
   * // Update one Submission
   * const submission = await prisma.submission.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SubmissionUpdateArgs>(args: Prisma.SelectSubset<T, SubmissionUpdateArgs<ExtArgs>>): Prisma.Prisma__SubmissionClient<runtime.Types.Result.GetResult<Prisma.$SubmissionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Submissions.
   * @param {SubmissionDeleteManyArgs} args - Arguments to filter Submissions to delete.
   * @example
   * // Delete a few Submissions
   * const { count } = await prisma.submission.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SubmissionDeleteManyArgs>(args?: Prisma.SelectSubset<T, SubmissionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Submissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Submissions
   * const submission = await prisma.submission.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SubmissionUpdateManyArgs>(args: Prisma.SelectSubset<T, SubmissionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Submissions and returns the data updated in the database.
   * @param {SubmissionUpdateManyAndReturnArgs} args - Arguments to update many Submissions.
   * @example
   * // Update many Submissions
   * const submission = await prisma.submission.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Submissions and only return the `id`
   * const submissionWithIdOnly = await prisma.submission.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SubmissionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SubmissionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubmissionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Submission.
   * @param {SubmissionUpsertArgs} args - Arguments to update or create a Submission.
   * @example
   * // Update or create a Submission
   * const submission = await prisma.submission.upsert({
   *   create: {
   *     // ... data to create a Submission
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Submission we want to update
   *   }
   * })
   */
  upsert<T extends SubmissionUpsertArgs>(args: Prisma.SelectSubset<T, SubmissionUpsertArgs<ExtArgs>>): Prisma.Prisma__SubmissionClient<runtime.Types.Result.GetResult<Prisma.$SubmissionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Submissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionCountArgs} args - Arguments to filter Submissions to count.
   * @example
   * // Count the number of Submissions
   * const count = await prisma.submission.count({
   *   where: {
   *     // ... the filter for the Submissions we want to count
   *   }
   * })
  **/
  count<T extends SubmissionCountArgs>(
    args?: Prisma.Subset<T, SubmissionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SubmissionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Submission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SubmissionAggregateArgs>(args: Prisma.Subset<T, SubmissionAggregateArgs>): Prisma.PrismaPromise<GetSubmissionAggregateType<T>>

  /**
   * Group by Submission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SubmissionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SubmissionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SubmissionGroupByArgs['orderBy'] }
      : { orderBy?: SubmissionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SubmissionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSubmissionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Submission model
 */
readonly fields: SubmissionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Submission.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SubmissionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  task<T extends Prisma.TaskDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaskDefaultArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  builder<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  kpiResults<T extends Prisma.Submission$kpiResultsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Submission$kpiResultsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KPIResultPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  supportingFiles<T extends Prisma.Submission$supportingFilesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Submission$supportingFilesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SupportingFilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Submission model
 */
export interface SubmissionFieldRefs {
  readonly id: Prisma.FieldRef<"Submission", 'String'>
  readonly taskId: Prisma.FieldRef<"Submission", 'String'>
  readonly builderId: Prisma.FieldRef<"Submission", 'String'>
  readonly workSummary: Prisma.FieldRef<"Submission", 'String'>
  readonly status: Prisma.FieldRef<"Submission", 'String'>
  readonly reviewNotes: Prisma.FieldRef<"Submission", 'String'>
  readonly amount: Prisma.FieldRef<"Submission", 'Float'>
  readonly reviewedAt: Prisma.FieldRef<"Submission", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Submission", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Submission", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Submission findUnique
 */
export type SubmissionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Submission
   */
  select?: Prisma.SubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Submission
   */
  omit?: Prisma.SubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionInclude<ExtArgs> | null
  /**
   * Filter, which Submission to fetch.
   */
  where: Prisma.SubmissionWhereUniqueInput
}

/**
 * Submission findUniqueOrThrow
 */
export type SubmissionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Submission
   */
  select?: Prisma.SubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Submission
   */
  omit?: Prisma.SubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionInclude<ExtArgs> | null
  /**
   * Filter, which Submission to fetch.
   */
  where: Prisma.SubmissionWhereUniqueInput
}

/**
 * Submission findFirst
 */
export type SubmissionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Submission
   */
  select?: Prisma.SubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Submission
   */
  omit?: Prisma.SubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionInclude<ExtArgs> | null
  /**
   * Filter, which Submission to fetch.
   */
  where?: Prisma.SubmissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Submissions to fetch.
   */
  orderBy?: Prisma.SubmissionOrderByWithRelationInput | Prisma.SubmissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Submissions.
   */
  cursor?: Prisma.SubmissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Submissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Submissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Submissions.
   */
  distinct?: Prisma.SubmissionScalarFieldEnum | Prisma.SubmissionScalarFieldEnum[]
}

/**
 * Submission findFirstOrThrow
 */
export type SubmissionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Submission
   */
  select?: Prisma.SubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Submission
   */
  omit?: Prisma.SubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionInclude<ExtArgs> | null
  /**
   * Filter, which Submission to fetch.
   */
  where?: Prisma.SubmissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Submissions to fetch.
   */
  orderBy?: Prisma.SubmissionOrderByWithRelationInput | Prisma.SubmissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Submissions.
   */
  cursor?: Prisma.SubmissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Submissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Submissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Submissions.
   */
  distinct?: Prisma.SubmissionScalarFieldEnum | Prisma.SubmissionScalarFieldEnum[]
}

/**
 * Submission findMany
 */
export type SubmissionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Submission
   */
  select?: Prisma.SubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Submission
   */
  omit?: Prisma.SubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionInclude<ExtArgs> | null
  /**
   * Filter, which Submissions to fetch.
   */
  where?: Prisma.SubmissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Submissions to fetch.
   */
  orderBy?: Prisma.SubmissionOrderByWithRelationInput | Prisma.SubmissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Submissions.
   */
  cursor?: Prisma.SubmissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Submissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Submissions.
   */
  skip?: number
  distinct?: Prisma.SubmissionScalarFieldEnum | Prisma.SubmissionScalarFieldEnum[]
}

/**
 * Submission create
 */
export type SubmissionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Submission
   */
  select?: Prisma.SubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Submission
   */
  omit?: Prisma.SubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionInclude<ExtArgs> | null
  /**
   * The data needed to create a Submission.
   */
  data: Prisma.XOR<Prisma.SubmissionCreateInput, Prisma.SubmissionUncheckedCreateInput>
}

/**
 * Submission createMany
 */
export type SubmissionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Submissions.
   */
  data: Prisma.SubmissionCreateManyInput | Prisma.SubmissionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Submission createManyAndReturn
 */
export type SubmissionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Submission
   */
  select?: Prisma.SubmissionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Submission
   */
  omit?: Prisma.SubmissionOmit<ExtArgs> | null
  /**
   * The data used to create many Submissions.
   */
  data: Prisma.SubmissionCreateManyInput | Prisma.SubmissionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Submission update
 */
export type SubmissionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Submission
   */
  select?: Prisma.SubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Submission
   */
  omit?: Prisma.SubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionInclude<ExtArgs> | null
  /**
   * The data needed to update a Submission.
   */
  data: Prisma.XOR<Prisma.SubmissionUpdateInput, Prisma.SubmissionUncheckedUpdateInput>
  /**
   * Choose, which Submission to update.
   */
  where: Prisma.SubmissionWhereUniqueInput
}

/**
 * Submission updateMany
 */
export type SubmissionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Submissions.
   */
  data: Prisma.XOR<Prisma.SubmissionUpdateManyMutationInput, Prisma.SubmissionUncheckedUpdateManyInput>
  /**
   * Filter which Submissions to update
   */
  where?: Prisma.SubmissionWhereInput
  /**
   * Limit how many Submissions to update.
   */
  limit?: number
}

/**
 * Submission updateManyAndReturn
 */
export type SubmissionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Submission
   */
  select?: Prisma.SubmissionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Submission
   */
  omit?: Prisma.SubmissionOmit<ExtArgs> | null
  /**
   * The data used to update Submissions.
   */
  data: Prisma.XOR<Prisma.SubmissionUpdateManyMutationInput, Prisma.SubmissionUncheckedUpdateManyInput>
  /**
   * Filter which Submissions to update
   */
  where?: Prisma.SubmissionWhereInput
  /**
   * Limit how many Submissions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Submission upsert
 */
export type SubmissionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Submission
   */
  select?: Prisma.SubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Submission
   */
  omit?: Prisma.SubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionInclude<ExtArgs> | null
  /**
   * The filter to search for the Submission to update in case it exists.
   */
  where: Prisma.SubmissionWhereUniqueInput
  /**
   * In case the Submission found by the `where` argument doesn't exist, create a new Submission with this data.
   */
  create: Prisma.XOR<Prisma.SubmissionCreateInput, Prisma.SubmissionUncheckedCreateInput>
  /**
   * In case the Submission was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SubmissionUpdateInput, Prisma.SubmissionUncheckedUpdateInput>
}

/**
 * Submission delete
 */
export type SubmissionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Submission
   */
  select?: Prisma.SubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Submission
   */
  omit?: Prisma.SubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionInclude<ExtArgs> | null
  /**
   * Filter which Submission to delete.
   */
  where: Prisma.SubmissionWhereUniqueInput
}

/**
 * Submission deleteMany
 */
export type SubmissionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Submissions to delete
   */
  where?: Prisma.SubmissionWhereInput
  /**
   * Limit how many Submissions to delete.
   */
  limit?: number
}

/**
 * Submission.kpiResults
 */
export type Submission$kpiResultsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KPIResult
   */
  select?: Prisma.KPIResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KPIResult
   */
  omit?: Prisma.KPIResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KPIResultInclude<ExtArgs> | null
  where?: Prisma.KPIResultWhereInput
  orderBy?: Prisma.KPIResultOrderByWithRelationInput | Prisma.KPIResultOrderByWithRelationInput[]
  cursor?: Prisma.KPIResultWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.KPIResultScalarFieldEnum | Prisma.KPIResultScalarFieldEnum[]
}

/**
 * Submission.supportingFiles
 */
export type Submission$supportingFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SupportingFile
   */
  select?: Prisma.SupportingFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SupportingFile
   */
  omit?: Prisma.SupportingFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SupportingFileInclude<ExtArgs> | null
  where?: Prisma.SupportingFileWhereInput
  orderBy?: Prisma.SupportingFileOrderByWithRelationInput | Prisma.SupportingFileOrderByWithRelationInput[]
  cursor?: Prisma.SupportingFileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SupportingFileScalarFieldEnum | Prisma.SupportingFileScalarFieldEnum[]
}

/**
 * Submission without action
 */
export type SubmissionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Submission
   */
  select?: Prisma.SubmissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Submission
   */
  omit?: Prisma.SubmissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubmissionInclude<ExtArgs> | null
}
